In [ ]:
import numpy as np
np.random.seed(5)
A = np.random.randint(0, 100, size=(9, 9))
print("Elements in Matrix")
print(A)

B = []

for i in range(0, A.shape[0], 1):
    temp = A[i, :].mean()
    B.append(temp)  # save the mean on the respective position of the B list
print(B)

# step 3 and 4
C = np.zeros((A.shape[0], A.shape[1]))
ZerosCount = 0
Non_zero_Count = 0

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if A[i, j] > B[i]:
            C[i, j] = 0
            ZerosCount = ZerosCount + 1
        else:
            C[i, j] = A[i, j]
            Non_zero_Count = Non_zero_Count + 1

if Non_zero_Count + ZerosCount == A.size:
    print("Updated matrix is verified")
else:
    print("non Validated")

print("Updated Matrix")
print(C)
print("Number of non zeros:", Non_zero_Count)
print("Number of zeros:", ZerosCount)

Elements in Matrix
[[99 78 61 16 73  8 62 27 30]
 [80  7 76 15 53 80 27 44 77]
 [75 65 47 30 84 86 18  9 41]
 [62  1 82 16 78  5 58  0 80]
 [ 4 36 51 27 31  2 68 38 83]
 [19 18  7 30 62 11 67 65 55]
 [ 3 91 78 27 29 33 89 85  7]
 [16 94 14 90 31  9 38 47 16]
 [ 5 34 45 59 24 13 31 32 76]]
[50.44444444444444, 51.0, 50.55555555555556, 42.44444444444444, 37.77777777777778, 37.111111111111114, 49.111111111111114, 39.44444444444444, 35.44444444444444]
Updated matrix is verified
Updated Matrix
[[ 0.  0.  0. 16.  0.  8.  0. 27. 30.]
 [ 0.  7.  0. 15.  0.  0. 27. 44.  0.]
 [ 0.  0. 47. 30.  0.  0. 18.  9. 41.]
 [ 0.  1.  0. 16.  0.  5.  0.  0.  0.]
 [ 4. 36.  0. 27. 31.  2.  0.  0.  0.]
 [19. 18.  7. 30.  0. 11.  0.  0.  0.]
 [ 3.  0.  0. 27. 29. 33.  0.  0.  7.]
 [16.  0. 14.  0. 31.  9. 38.  0. 16.]
 [ 5. 34.  0.  0. 24. 13. 31. 32.  0.]]
Number of non zeros: 44
Number of zeros: 37


In [ ]:
import numpy as np
np.random.seed(5)
matrix = np.random.randint(0, 100, size=(4,4))
print("Elements in Matrix")
print(matrix)


# Get dimensions of the original matrix
rows, cols = matrix.shape

# Create a matrix to store max values
max_matrix = np.zeros((rows//2, cols//2), dtype=int)

# Iterate over the matrix in steps of 2
for i in range(0, rows, 2):
    for j in range(0, cols, 2):
        # Extract 2x2 submatrix
        submatrix = matrix[i:i+2, j:j+2]
        print(submatrix)

        temp = submatrix
        max_value = temp.max()
        print(f"Max value: {max_value}")
        print()  # Add a blank line between submatrices

        # Store max value in max_matrix
        max_matrix[i//2, j//2] = max_value

# Print the matrix of max values
print("Matrix of max values:")
print(max_matrix)

Elements in Matrix
[[99 78 61 16]
 [73  8 62 27]
 [30 80  7 76]
 [15 53 80 27]]
[[99 78]
 [73  8]]
Max value: 99

[[61 16]
 [62 27]]
Max value: 62

[[30 80]
 [15 53]]
Max value: 80

[[ 7 76]
 [80 27]]
Max value: 80

Matrix of max values:
[[99 62]
 [80 80]]


In [ ]:
import pandas as pd
#read the csv
path='/content/ign.csv'
data=pd.read_csv(path)
print(type(data))
print(data.shape)
data.head()

<class 'pandas.core.frame.DataFrame'>
(18625, 10)


score_phrase                                              title  \
0      Amazing                            LittleBigPlanet PS Vita   
1      Amazing  LittleBigPlanet PS Vita -- Marvel Super Hero E...   
2        Great                               Splice: Tree of Life   
3        Great                                             NHL 13   
4        Great                                             NHL 13   

                                                 url          platform  score  \
0             /games/littlebigplanet-vita/vita-98907  PlayStation Vita    9.0   
1  /games/littlebigplanet-ps-vita-marvel-super-he...  PlayStation Vita    9.0   
2                          /games/splice/ipad-141070              iPad    8.5   
3                      /games/nhl-13/xbox-360-128182          Xbox 360    8.5   
4                           /games/nhl-13/ps3-128181     PlayStation 3    8.5   

        genre editors_choice  release_year  release_month  release_day  
0  Platformer              Y          2012              9           12  
1  Platformer              Y          2012              9           12  
2      Puzzle              N          2012              9           12  
3      Sports              N          2012              9           11  
4      Sports              N          2012              9           11

In [ ]:
data.tail()

score_phrase                                    title  \
18620         Good                Tokyo Mirage Sessions #FE   
18621      Amazing        LEGO Star Wars: The Force Awakens   
18622     Mediocre  Star Ocean: Integrity and Faithlessness   
18623  Masterpiece                                   Inside   
18624  Masterpiece                                   Inside   

                                                     url       platform  \
18620  /games/fire-emblem-x-shin-megami-tensei/wii-u-...          Wii U   
18621  /games/lego-star-wars-the-force-awakens/ps4-20...  PlayStation 4   
18622                   /games/star-ocean-5/ps4-20035681  PlayStation 4   
18623             /games/inside-playdead/xbox-one-121435       Xbox One   
18624                 /games/inside-playdead/pc-20055740             PC   

       score              genre editors_choice  release_year  release_month  \
18620    7.6                RPG              N          2016              6   
18621    9.0  Action, Adventure              Y          2016              6   
18622    5.8                RPG              N          2016              6   
18623   10.0          Adventure              Y          2016              6   
18624   10.0          Adventure              Y          2016              6   

       release_day  
18620           29  
18621           29  
18622           28  
18623           28  
18624           28

In [ ]:
data.loc[2:5]

score_phrase                      title  \
2        Great       Splice: Tree of Life   
3        Great                     NHL 13   
4        Great                     NHL 13   
5         Good  Total War Battles: Shogun   

                                          url       platform  score     genre  \
2                   /games/splice/ipad-141070           iPad    8.5    Puzzle   
3               /games/nhl-13/xbox-360-128182       Xbox 360    8.5    Sports   
4                    /games/nhl-13/ps3-128181  PlayStation 3    8.5    Sports   
5  /games/total-war-battles-shogun/mac-142565      Macintosh    7.0  Strategy   

  editors_choice  release_year  release_month  release_day  
2              N          2012              9           12  
3              N          2012              9           11  
4              N          2012              9           11  
5              N          2012              9           11

In [ ]:
data[['score','platform']]

score          platform
0        9.0  PlayStation Vita
1        9.0  PlayStation Vita
2        8.5              iPad
3        8.5          Xbox 360
4        8.5     PlayStation 3
...      ...               ...
18620    7.6             Wii U
18621    9.0     PlayStation 4
18622    5.8     PlayStation 4
18623   10.0          Xbox One
18624   10.0                PC

[18625 rows x 2 columns]

In [ ]:
score=data['score']
avg=score.mean()
mn=score.min()
mx=score.max()
var=score.var()
std=score.std()
print("Variance",var)
print("standard deviation ",std)
print("Minimum",mn)
print("maximum",mx)
print("Average",avg)

Variance 2.9300396571646026
standard deviation  1.7117358608046402
Minimum 0.5
maximum 10.0
Average 6.950459060402685


In [ ]:
platform=data['platform'].unique()
platform

array(['PlayStation Vita', 'iPad', 'Xbox 360', 'PlayStation 3',
       'Macintosh', 'PC', 'iPhone', 'Nintendo DS', 'Nintendo 3DS',
       'Android', 'Wii', 'PlayStation 4', 'Wii U', 'Linux',
       'PlayStation Portable', 'PlayStation', 'Nintendo 64', 'Saturn',
       'Lynx', 'Game Boy', 'Game Boy Color', 'NeoGeo Pocket Color',
       'Game.Com', 'Dreamcast', 'Dreamcast VMU', 'WonderSwan', 'Arcade',
       'Nintendo 64DD', 'PlayStation 2', 'WonderSwan Color',
       'Game Boy Advance', 'Xbox', 'GameCube', 'DVD / HD Video Game',
       'Wireless', 'Pocket PC', 'N-Gage', 'NES', 'iPod', 'Genesis',
       'TurboGrafx-16', 'Super NES', 'NeoGeo', 'Master System',
       'Atari 5200', 'TurboGrafx-CD', 'Atari 2600', 'Sega 32X', 'Vectrex',
       'Commodore 64/128', 'Sega CD', 'Nintendo DSi', 'Windows Phone',
       'Web Games', 'Xbox One', 'Windows Surface', 'Ouya',
       'New Nintendo 3DS', 'SteamOS'], dtype=object)

In [ ]:
games_number=data['release_year'].value_counts()
games_number

release_year
2008    1915
2009    1687
2007    1610
2010    1363
2006    1208
2005    1088
2011    1073
2000    1045
2004     997
2003     969
2002     936
1999     775
2012     753
2013     696
2001     688
2014     537
2015     365
1998     339
2016     226
1997     205
1996     149
1970       1
Name: count, dtype: int64

In [ ]:
ind=data['platform']=='PC'
newData=data[ind]
print("Total no of pc games are: ",newData.shape[0])

Total no of pc games are:  3370


In [ ]:
data['platform'].value_counts()

platform
PC                      3370
PlayStation 2           1686
Xbox 360                1631
Wii                     1366
PlayStation 3           1356
Nintendo DS             1045
PlayStation              952
Wireless                 910
iPhone                   842
Xbox                     821
PlayStation Portable     633
Game Boy Advance         623
GameCube                 509
Game Boy Color           356
Nintendo 64              302
Dreamcast                286
PlayStation 4            277
Nintendo DSi             254
Nintendo 3DS             225
Xbox One                 208
PlayStation Vita         155
Wii U                    114
iPad                      99
Lynx                      82
Macintosh                 81
Genesis                   58
NES                       49
TurboGrafx-16             40
Android                   39
Super NES                 33
NeoGeo Pocket Color       31
N-Gage                    30
Game Boy                  22
iPod                      17
Sega 

In [ ]:
form=data['platform'].unique()
form

array(['PlayStation Vita', 'iPad', 'Xbox 360', 'PlayStation 3',
       'Macintosh', 'PC', 'iPhone', 'Nintendo DS', 'Nintendo 3DS',
       'Android', 'Wii', 'PlayStation 4', 'Wii U', 'Linux',
       'PlayStation Portable', 'PlayStation', 'Nintendo 64', 'Saturn',
       'Lynx', 'Game Boy', 'Game Boy Color', 'NeoGeo Pocket Color',
       'Game.Com', 'Dreamcast', 'Dreamcast VMU', 'WonderSwan', 'Arcade',
       'Nintendo 64DD', 'PlayStation 2', 'WonderSwan Color',
       'Game Boy Advance', 'Xbox', 'GameCube', 'DVD / HD Video Game',
       'Wireless', 'Pocket PC', 'N-Gage', 'NES', 'iPod', 'Genesis',
       'TurboGrafx-16', 'Super NES', 'NeoGeo', 'Master System',
       'Atari 5200', 'TurboGrafx-CD', 'Atari 2600', 'Sega 32X', 'Vectrex',
       'Commodore 64/128', 'Sega CD', 'Nintendo DSi', 'Windows Phone',
       'Web Games', 'Xbox One', 'Windows Surface', 'Ouya',
       'New Nintendo 3DS', 'SteamOS'], dtype=object)

In [ ]:
ind=data['score_phrase']=='Amazing'
newData=data[ind]
print("Total no of amazing games are: ",newData.shape[0])

Total no of amazing games are:  1804


In [ ]:
ind=(data['score_phrase']=='Amazing')&(data['platform']=='PC')
nData=data[ind]
print("total no of amazing pc games are",nData.shape[0])

total no of amazing pc games are 351
